module.exports = {
  caseType:'revenue_cycle_claim', initialState:'eligibility_pending',
  states:['eligibility_pending','encounter_verified','coding_review','claim_ready','submitted','remittance_received','denied','appealed','paid','reconciled'],
  createRoles:['billing_specialist','revenue_cycle_manager'],
  evidenceKinds:['eligibility_response','encounter_digest','coding_source_version','claim_payload_digest','clearinghouse_receipt','remittance_digest','denial_reason','appeal_packet','payment_ledger'],
  requiredSignals:['eligibilityStatus','codeSetVersion','coverageVersion','encounterComplete','claimControlNumber','policyVersion'],
  assessmentRoles:['billing_specialist','certified_coder','denial_specialist','revenue_cycle_manager'],
  auditRoles:['revenue_cycle_manager','certified_coder'],
  connectorRoles:['billing_specialist','revenue_cycle_manager'],
  professionalBoundary:'The workflow does not autonomously commit codes, claims, appeals, or payments; qualified staff retain responsibility.',
  connectors:[
    {name:'fhir_ehr',purpose:'eligibility and encounter references'},
    {name:'clearinghouse',purpose:'claim and remittance receipts'},
    {name:'payer',purpose:'coverage and denial status'},
    {name:'coding_coverage',purpose:'licensed version references'},
    {name:'payments',purpose:'payment ledger references'},
    {name:'document_storage',purpose:'encrypted appeal evidence pointers'},
  ],
  transitions:[
    {from:'eligibility_pending',action:'verify_encounter',to:'encounter_verified',roles:['billing_specialist'],requiresEvidence:true},
    {from:'encounter_verified',action:'submit_coding_review',to:'coding_review',roles:['billing_specialist'],requiresEvidence:true},
    {from:'coding_review',action:'approve_codes',to:'claim_ready',roles:['certified_coder'],requiresEvidence:true,dualControl:true},
    {from:'claim_ready',action:'record_submission',to:'submitted',roles:['billing_specialist'],requiresEvidence:true},
    {from:'submitted',action:'post_remittance',to:'remittance_received',roles:['payment_poster'],requiresEvidence:true,dualControl:true},
    {from:'remittance_received',action:'route_denial',to:'denied',roles:['denial_specialist'],requiresEvidence:true},
    {from:'denied',action:'submit_appeal',to:'appealed',roles:['denial_specialist'],requiresEvidence:true,dualControl:true},
    {from:'remittance_received',action:'record_payment',to:'paid',roles:['payment_poster'],requiresEvidence:true},
    {from:'paid',action:'reconcile',to:'reconciled',roles:['revenue_cycle_manager'],requiresEvidence:true,dualControl:true},
  ],
  assess:x=>({disposition:x.eligibilityStatus==='verified'&&x.encounterComplete?'certified_coding_review_required':'hold_for_source_correction',codingCommitment:null,versions:{codes:x.codeSetVersion,coverage:x.coverageVersion}}),
};
